version: "3.5"
services:
  app:
    build:
      context: '.'
      target: development
    volumes:
      - ".:/usr/src/app"
      - "dotconfig:/root/.config"
    working_dir: /usr/src/app
    environment:
      HOST: '0.0.0.0'
      PORT: '8080'
    env_file: config.env
    ports:
      - "8080:8080"

volumes:
  dotconfig:
    # created by bootstrap.sh script using gcloud container
    external: true
